#ifndef LANG_WORDS_H
#define LANG_WORDS_H

#define IDENTIFIER 600
#define NEWLINE 601
#define FLOAT_VALUE 602
#define QUIT 665
#define END_OF_FILE 666

//OPERATORS
#define OPE_SLASH_EQ 900
#define OPE_TWO_POINTS 901
#define OPE_THREE_POINTS 902
#define OPE_AND_EQ 903
#define OPE_AND_AND 904
#define OPE_VERT_EQ 905
#define OPE_VERT_VERT 906
#define OPE_MINUS_EQ 907
#define OPE_MINUS_MINUS 908
#define OPE_PLUS_EQ 909
#define OPE_PLUS_PLUS 910
#define OPE_LESSTHAN_EQ 911
#define OPE_LESSTHAN_LESSTHAN 912
#define OPE_LESSTHAN_LESSTHAN_EQ 913
#define OPE_LESSTHAN_MORETHAN 914
#define OPE_LESSTHAN_MORETHAN_EQ 915
#define OPE_MORETHAN_EQ 916
#define OPE_MORETHAN_MORETHAN_EQ 917
#define OPE_MORETHAN_MORETHAN_MORETHAN_EQ 918
#define OPE_MORETHAN_MORETHAN 919
#define OPE_MORETHAN_MORETHAN_MORETHAN 920
#define OPE_EXCL_EQ 921
#define OPE_EXCL_LESSTHAN_MORETHAN 922
#define OPE_EXCL_LESSTHAN_MORETHAN_EQ 923
#define OPE_EXCL_LESSTHAN 924
#define OPE_EXCL_LESSTHAN_EQ 925
#define OPE_EXCL_MORETHAN 926
#define OPE_EXCL_MORETHAN_EQ 927
#define OPE_EQ_EQ 928
#define OPE_TIMES_EQ 929
#define OPE_PERC_EQ 930
#define OPE_HAT_EQ 931
#define OPE_HAT_HAT 932
#define OPE_HAT_HAT_EQ 933
#define OPE_VIRG_EQ 934
#define OPE_EQ_MORE 935


#endif
